### ISSUE TITLE
Auto-merge flag during PR creation

### ISSUE THREAD

**Issue by bbednarek** [Skyscanner/turbolift#90] opened 2022-12-21 16:37 UTC
# Description
It would be very helpful to add `--auto-merge` flag to `turbolift create-prs` command.

# Motivation
In case of huge amount of repos it would be very convenient to enable auto-merge (if the repo has such function of course), so if all of the checks are green, then PR would be merged automatically.

**Comment by rnorth** [comment] 2022-12-30 13:09
This sounds like a good suggestion, thank you. Would you like to raise a PR to add this feature?

**Comment by bbednarek** [comment] 2023-02-17 09:42
@rnorth I am not familiar with go lang, but next week I plan to learn it, so I might give a try to raise a PR :)

**Comment by oleg-smartone** [comment] 2024-11-15 02:14
Hey! I tried implementing this a few different ways, but ran into some tricky API challenges. The main issue is that `gh pr create` doesn't have an `--auto` flag by design. This means we need to chain together `gh pr merge` right after creating the PR, which can be problematic - there's a race condition where the PR might not exist yet when we try to merge it as well as you'd have to obtain the actual PR number. On top of that, `gh pr merge` needs both the PR number and merge strategy flags (`--rebase`, `--squash`, or `--merge`), making it pretty complex to design a clean, generic API for turboshift.

**Comment by Moshyfawn** [comment] 2024-11-15 14:19
Hey! I tried implementing this a few different ways, but ran into some tricky API challenges. The main issue is that `gh pr create` doesn't have an `--auto` flag by design. This means we need to chain together `gh pr merge` right after creating the PR, which can be problematic - there's a race condition where the PR might not exist yet when we try to merge it as well as you'd have to obtain the actual PR number. On top of that, `gh pr merge` needs both the PR number and merge strategy flags (`--rebase`, `--squash`, or `--merge`), making it pretty complex to design a clean, generic API for turboshift.

**Comment by rnorth** [comment] 2024-11-18 10:12
Ah yes, I can see now why this is a pain.

I think I agree with not adding this to turbolift then. The `turbolift foreach gh pr merge` looks good for situations where the person running turbolift has permissions to do the merge.

**Comment by sledigabel** [comment] 2024-11-18 10:59
@Dan7-7-7 the difference here is that as a user you have permission over your own PR and declaring it as a draft.
You might not have the permissions to do a merge?

**Comment by Dan7-7-7** [comment] 2024-11-18 11:10
True perhaps best just to use the workaround then

**Comment by Dan7-7-7** [comment] 2024-11-18 15:10
Closing as we don't currently think this should be a feature of the tool, and a workaround has been given

**Closed by Dan7-7-7** 2024-11-18 15:10 UTC
Labels: good first issue, help wanted
